version: '3.5'

services:
  frontend:
    image: frontend
    build: ./frontend
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    image: backend
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/logs.txt:/backend-example-docker/logs.txt
    container_name: backend


